### ISSUE TITLE
Run MONAI Label App on a volume that is loaded into the Slicer scene

### ISSUE THREAD

**Issue by diazandr3s** [Project-MONAI/MONAILabel#147]
**Is your feature request related to a problem? Please describe.**

There is no way to run a MONAI Label App on a volume that is loaded into the scene. Without giving users the option to use MONAILabel to segment their own data, the module remains a hardcore developer tool.  

CC @lassoan 

**Describe the solution you'd like**

The best would be if MONAILabel implemented the AIAA API for uploading data and runnning inference so that we can use the current AIAA Segment Editor effect with MONAILabel apps. 

**Describe alternatives you've considered**
Specify the images' folder before starting MONAI Label server

**Additional context**

**Comment by diazandr3s** [comment]
What about having the set up "Data locally, inference remotely"?

**Comment by SachidanandAlle** [comment]
We have the APIs to push the data from client/slicer to MONAILabel server.  Action is added into slicer https://github.com/Project-MONAI/MONAILabel/pull/156
Or even you can run inference by passing raw image instead of image id.

<img src="https://user-images.githubusercontent.com/7339051/123954190-05c93800-d9a0-11eb-98ea-e036f25ba5cf.png" width="300"/>
