### ISSUE TITLE
Latest changes in Slicer plugin aren't reflected in daily Slicer

### ISSUE THREAD

**Issue by diazandr3s** [Project-MONAI/MONAILabel#407]
The latest version of Slicer (https://download.slicer.org/) doesn't contain the latest changes made in the MONAI Label plugin. The scribbles module isn't working when activating the MONAI Label Module from the Extension Manager. However, when adding the path from the repository, it works

CC @lassoan

**Comment by lassoan** [comment]
MONAILabel is only available for Slicer Preview Release. Each night a new release is built along with all extensions. However, it is not feasible to rebuild all packages are for the hundreds of all the previous nightly versions.

MONAILabel is built every night from the `main` branch (see [here](https://github.com/Slicer/ExtensionsIndex/blob/master/MONAILabel.s4ext#L10)), but since it is only available for the Preview Release, to upgrade to the latest MONAILabel version, you need to download&install the latest Slicer Preview Release.

**Comment by masadcv** [comment]
So I just tried the latest preview. It does seem to work on my end (please do verify if this is the case @diazandr3s). I will also give a try on one other machine that I have access to. The only missing thing is the icons for additional button in scribbles that were added (see screenshots below).

![Screenshot from 2021-09-22 14-35-31](https://user-images.githubusercontent.com/3410225/134353941-dc755a5f-9c2c-4bc7-930c-dce517838b1e.png)

![Screenshot from 2021-09-22 14-38-05](https://user-images.githubusercontent.com/3410225/134354195-590e6705-d00d-4068-8f53-0d1a2545b539.png)

I narrowed this down to adding relevant Resource files in https://github.com/Project-MONAI/MONAILabel/blob/main/plugins/slicer/MONAILabel/CMakeLists.txt - I will do a quick PR to fix this.

**Comment by diazandr3s** [comment]
> MONAILabel is only available for Slicer Preview Release. Each night a new release is built along with all extensions. However, it is not feasible to rebuild all packages are for the hundreds of all the previous nightly versions.
> 
> MONAILabel is built every night from the `main` branch (see [here](https://github.com/Slicer/ExtensionsIndex/blob/master/MONAILabel.s4ext#L10)), but since it is only available for the Preview Release, to upgrade to the latest MONAILabel version, you need to download&install the latest Slicer Preview Release.

Thanks @lassoan for the clarification

**Comment by diazandr3s** [comment]
Closing this issue.
