### ISSUE TITLE
DeepEdit development & evaluation for Cold Start

### ISSUE THREAD

**Issue by pdogra89** [Project-MONAI/MONAILabel#47]
Aligned to 301 workflow

**Comment by diazandr3s** [comment]
- Checked the DeepEdit training in MONAILabel and it is working well for heart App. One Epoch takes around 30 seconds whe using 3 "manually" annotated images
- Still evaluating non-linear transforms to be used in heart App in order to get better results after model is trained
- Will check cold-start training on a third dataset and see how that works

**Comment by SachidanandAlle** [comment]
@diazandr3s can you add the stats/progress and close the issue if it's completed

**Comment by diazandr3s** [comment]
Just added the updated plots obtained for the left atrium and spleen App evaluation. In the wiki I also explained the time took per epoch on each App and the number of images used to train and validate both Apps
