### ISSUE TITLE
Incorrect filename truncation

### ISSUE THREAD

**Issue by SlicerMorph** [Project-MONAI/MONAILabel#566]
**Describe the bug**

When I use the Next Sample button, the retrieved displayed volume name is incorrect. That's because i believe parser incorrectly cuts at the volume name at "-" sign of the volume. Below is the log from the python interactor, displaying the correct volume name. In slicer, regardless of the volume, all retrieved volumes are displayed as __15.5_baseline__ in Slicer, which confuses the user. 

```
Check if file exists/shared locally: /workspace/undeterminedSex_AAMN_N305-17-e15.5_baseline.nii.gz => False
http://127.0.0.1:8000/datastore/image?image=undeterminedSex_AAMN_N305-17-e15.5_baseline
```
![image](https://user-images.githubusercontent.com/45026482/147365618-c92572ef-0904-4509-ae7a-c2da8cdf01bb.png)

**Comment by SachidanandAlle** [comment]
It's not a bug.. the last 20 chars of original filename is shown to avoid combo box stretched by too much.. and becomes difficult to read/identify

**Comment by SlicerMorph** [comment]
It may not be a programmatic bug, it is a bug for user. How am I going to know which file I am segmenting then?

**Comment by lassoan** [comment]
Full string could be set as tooltip.

**Comment by SachidanandAlle** [comment]
Currently logs can help you to get full details.. u can see them under python console inside slicer...
Or as suggested by @lassoan .. if you can add a small fix to add tooltip and raise a PR.. will be helpful

**Comment by pwrightkcl** [comment]
I need a way to view the full filename in Slicer without access to the logs. I will set up and run the server, but a clinician will label the images on a different PC, so using the server log is impractical for my use case (the clinician would need to note the time he loaded an image, and I would need to go back and track it down, which creates extra work and risk of error).

My images have necessarily long filenames. When I load an image in Slicer manually, I can see the full filename in the Volumes module. The display window truncates the filename, but whereas MONAI label just shows the last few characters, Slicer truncates as "head...tail", which is more likely to be identifiable (in my case most of my filename tails are identical).

Would it be possible to have MONAI label use its truncated filename only for its dropdown, but let Slicer handle the full filename the normal way?

**Comment by pwrightkcl** [comment]
I don't know how to do that, sorry.

**Comment by diazandr3s** [comment]
Thanks for reporting this, @pwrightkcl.

I'm happy to show you how you can do what @SachidanandAlle suggested. It could be an opportunity to learn how to customise the MONAI Label Slicer module. Everything is written in Python :)

```
1/ Add a settings flag to show full filename
```

Here is an example of a flag in MONAI Label Slicer module: https://github.com/Project-MONAI/MONAILabel/blob/main/plugins/slicer/MONAILabel/MONAILabel.py#L154-L163 

```
2/ When you creat the volume node.. you can set the full or truncated based on the above flag.
```
Once the flag is created, here is how you could use it: https://github.com/Project-MONAI/MONAILabel/blob/main/plugins/slicer/MONAILabel/MONAILabel.py#L1223

What @SachidanandAlle suggested is to use the flag when you load the volume here: https://github.com/Project-MONAI/MONAILabel/blob/main/plugins/slicer/MONAILabel/MONAILabel.py#L1210-L1221

Hope that helps

**Comment by lassoan** [comment]
Combobox sizing is a surprisingly complicated topic. Having a long string in a comobox can mess up layouts. So, in general you cannot just let strings displayed without some kind of control over the displayed length.

One option is to shorten the strings, but I agree that it can be problematic, because you may want to store a lot of relevant information there.

Another option is to use eliding (remove beginning, middle, or end of the string and replace with `...`). Qt's stock QComboBox does not support eliding, but in ctkComboBox and derived classes you can enable eliding using the `elideMode` property.

As a side note, filename should be generally limited to a few ten characters because total file path length is quite short on Windows (depending on what file access API isand file system is used).

If your workflow relies on the user taking note of filenames then it may make sense to add a small button (it could be just a "copy" icon) for copying the filename to the clipboard. Maybe it could be a generally useful feature.

**Comment by lassoan** [comment]
> All I wanted was for the MONAI label plugin to let Slicer handle the filename the way it usually does, and only truncate it in the MONAI label Master Volume dropdown, instead of truncating it throughout Slicer.

There is a difference between the user loading a file from a folder where that data persistently stored; and loading a file from a temporary folder (for example a folder that stores temporary data that is downloaded from a server). The filename should be cleared or set to a random string if it is read from a temporary location. It looks like MONAILabel clears the filename (you can see that in Volumes module), so I think MONAILabel sets the filename correctly.

The node name is often displayed on screen and therefore it is better to keep it short (10-20 characters). If MONAILabel tends to create long filenames then that may worth revisiting (e.g., if it adds a suffix then use `seg` instead of `segmentation`). However, long node names should not cause too much trouble for modules. If MONAILabel does not show long node names well (e.g., clips the end or makes the GUI layout very wide) then that could be improved (e.g., always elide the middle of long strings). But none of these seem to make a dramatic difference for the workflows that I have in mind.

@pwrightkcl could you describe your workflow and the reason for having long names and the reasons for needing to see them? Do you really just need to see them or copy them to some other locations or cross-reference them with some other data,...? We may find a much better solution to your needs than just displaying longer names.

**Comment by SachidanandAlle** [comment]
I agree as @lassoan said.. 

for example, u might just need some copy action button (instead of displaying long name) somewhere in the `Tools` section of monailabel plugin..

may be you can explain your post actions.  there may be a simple ways to get it done

**Comment by pwrightkcl** [comment]
This is my use case:

- I set up the MONAI label server, with its dataset, start it running, and give the URL to my clinician colleague.
- The clinician connects to the server using the MONAI label plugin in Slicer and works through the unlabelled images with the standard MONAI label flow:
  - "Next Sample" - MONAI label loads the next unlabelled image, chosen at random
  - Slicer displays the image
  - "Run Auto Segmentation"
  - MONAI label adds estimated labels to the image
  - Clinician makes manual corrections to labels as needed
  - "Submit Label"
  - MONAI label saves the labels as NIfTI and uploads them to the MONAI label server, where they are organized so each label image can be matched with its base image.
- The clinician wants to be able to note images where the model struggles to produce good labels, for example there is an unusual lesion, or the image has a bad artefact. This is where he needs a filename or another way to identify individual images.

Just to be clear, I am interested in the name of the base image, loaded in the first step. It happens that MONAI label does not generate a new filename for its labels, but places them in a subdirectory with the same name as the base image. So the base name of the label image would not be longer than the base name of the base image. Regardless, my use case does not concern the name of the label image.

One place to uniquely identify the image is the slice view, which is probably the first place the user looks. For a local image, Slicer shows the elided base name, but MONAI label shows the last 20 characters. For my files, the elided name is usually sufficient for unique ID, and in most other cases should be more likely unique than only head or tail. I assume this is "node name" not "file name", since the latter is cleared, but I'm new to the lingo so correct me if I'm wrong. I don't know if Slicer sets the node name internally to the elided string or if this is done on the fly for display in the slice view. Either way, I would prefer if MONAI label allowed Slicer to show the elided name in the slice view like it normally does. This might mean creating a shorter node name on the fly when making the "Master Volume" dropdown, if Slicer's elided node name is too long for that. I believe this would be efficient and perhaps more consistent, because it sounds like Slicer shows the node name in many places, but MONAI label only shows it in one.

I don't think the image name in the slice view is copyable as text. For copying, it would be more parsimonious to reuse an existing element than creating a special one if possible. The obvious place to me is the file name box in the Volumes module, but it sounds like it is mandatory to clear this. For MONAI label, the downloaded file has the same base name as the one on the server. @diazandr3s can correct me if I'm wrong, but I think that is always the case. The Volumes module only displays base name for local images, so at least in terms of information displayed, it would be a persistent name in both cases. Obviously there is a lot more going on behind the scenes that I don't understand so maybe this is impossible. Is there anywhere the node name is shown in copyable form? If file name has to be cleared and node name has to be elided, is there any way to store the full base name of a downloaded file, or would it be necessary to create a new variable just for MONAI label to use for this? If someone else take on this problem, I wouldn't want them to end up creating new entities unnecessarily, and potentially make life more complex for others in the future.

About the filename length: The images are organised according to [BIDS](https://bids.neuroimaging.io/). They are supplied to me with patient (subject) IDs replaced with 30 character hashes. These form part of the filename along with other BIDS entities describing the image, so they can get quite long, although I do not think any reach 100 characters.

Example:

`sub-0123456789abcdef0123456789abcd_ses-12345678_run-3_acq-Brain0625mm_rec-Tilt1_ct.nii`

I could, for the sake of the Slicer MONAI label plug in, rename all the images to < 20 characters, but I would need to keep a key and revert the names of the resulting labels to match the original filenames. That creates extra work that I would prefer to avoid.

At the moment the workaround is to have the clinician note the time they viewed the images, and for me to inspect the server logs to find the full filename. That relies on the server clock and the clinician's local PC clock both being correct (or I suppose consistently wrong). At least the former is something I can do!

**Comment by lassoan** [comment]
Thank you, this description was very useful.

> The clinician wants to be able to note images where the model struggles to produce good labels, for example there is an unusual lesion, or the image has a bad artefact. This is where he needs a filename or another way to identify individual images.

This is a very common need. I think in MONAILabelReview there is already support for adding notes to labeled images when they are uploaded to the server. Until it becomes available in MONAILabel, there are several quick workarounds.

>  Is there anywhere the node name is shown in copyable form?

Probably the easiest is the Data module. You can double-click on the node name and then hit Ctrl-C to copy it to the clipboard.

> I could, for the sake of the Slicer MONAI label plug in, rename all the images to < 20 characters, but I would need to keep a key and revert the names of the resulting labels to match the original filenames. That creates extra work that I would prefer to avoid.

If you use folder structure to organize your data then indeed you cannot do much about this. It is easier to handle the long names in the application than complicating things by keeping multiple copies of files with shortened names.

**Comment by lassoan** [comment]
I've pushed a change that makes the node name displayed with eliding the center:

https://github.com/Project-MONAI/MONAILabel/pull/841

Could you please check if it solves your problem? (just need to change a few lines in the MONAILabel module's .ui file)

**Comment by pwrightkcl** [comment]
> I've pushed a change that makes the node name displayed with eliding the center:
> 
> #841
> 
> Could you please check if it solves your problem? (just need to change a few lines in the MONAILabel module's .ui file)

Thanks for this. I'd be happy to try it out. I haven't installed a Slicer plugin manually by pulling code from Gitlab before, but I expect there are instructions here.

I think that the following line would also need to change, because it truncates the node name at the moment the new image is loaded:
https://github.com/Project-MONAI/MONAILabel/blob/4fd1c64aed2f00383094d2b100593695daa45ca9/plugins/slicer/MONAILabel/MONAILabel.py#L1206

**Comment by lassoan** [comment]
You don't need to install the plugin manually, just install it as usual and modify the files locally as needed. If you reinstall MONAILabel today then you'll get the elided combobox, so you can just make your suggested modification to test if everything works well. After you have a solution that you tested and works well for you then please submit a pull request. Thank you!

**Comment by pwrightkcl** [comment]
I tested out my proposed change and it didn't break anything. It did restore the usual elided node name in the slice view, same as for local loads.

![image](https://user-images.githubusercontent.com/32168177/174341868-54c3cbf2-a5b9-48f0-b792-2422e6484a19.png)

However, in the dropdown, the name appears full, at at least what is visible is not elided. I would look into this, but I don't know how the elision works, or Qt in general. Sorry!

![image](https://user-images.githubusercontent.com/32168177/174341930-d9eb2335-36b5-401f-960c-bfc262484cab.png)

I've made a pull request #842. I suggest either double-checking the code that elides the dropdown (maybe there are lines that only get run when the image is loaded?) or feel free to just reject it.

I also noticed that even though the base image node name is shortened, the segmentation node name in the Data module has the full base image filename, so I can always get it from there.
