### ISSUE TITLE
Fix mode/deepedit interaction based on user/clinician feedback

### ISSUE THREAD

**Issue by SachidanandAlle** [Project-MONAI/MONAILabel#582]
Case-1: If user wants to add dynamically new labels and doesn't like changing code/model for adding new labels
Case-2: If user wants to update all segments at once even if he/she is clicking one specific organ
Case-3: Lock update on specific segment

Case-2 and Case-3 are supported through config/check-box for user.  However for Case-2 the implementation is at client side and it silently drops the segments for other organs.

**Comment by diazandr3s** [comment]
I'm working with radiologists and another researcher (Paul Wright @pwrightkcl) to customise deepedit app for haemorrhage and ventricle segmentation (multilabel) on brain CT images. The idea is to get feedback from them after using MONAI Label. @pwrightkcl please keep me honest here? Is there anything else we should comment on here?

Specifically, this issue was opened for a slightly different purpose. I don't think comparing multiple single label against multilabel segmentation models makes sense. What do you think @mjorgecardoso

**Comment by SachidanandAlle** [comment]
I guess this is done.  If something needs to be addressed, feel free to reopen the issue
