### ISSUE TITLE
Options table incorrect

### ISSUE THREAD

**Issue by rijobro** [Project-MONAI/MONAILabel#612]
If I launch a training using `PersistentDataset` instead of `CacheDataset`, then reload the connection to the MONAI server, the table is reverted to its default, not the options that are being used for the current training.

**Comment by SachidanandAlle** [comment]
There is no DB kind of thing in monai label server..  server will always serve the default configs by design.

However client side saving the configs when user modifies can be implemented... like in 3D Slicer/OHIF viewer.  This is not a server-side feature to save the settings for the user.. however client needs to take of cherry-pick the config updates in such cases, when server/config/model is refreshed etc..

We are looking forward for contributions to add such simple enhancements at the client side (for both 3D Slicer and OHIF)

**Comment by SachidanandAlle** [comment]
as mentioned, this can be more client side.. either can be stored in cookies etc.. per user session.
and recently we have updated the interface for options table in 3D slicer to be much compact and useful.

looking for some contributions at the 3D slicer or plugin side to adding the feature.

**Comment by SachidanandAlle** [comment]
we have added bunch of ui improvements (except cookie for options.. which is kind of complicated and not in current scope to maintain client side sessions).  otherwise these improvements shall be more helpful for easier actions related train/infer options
