### ISSUE TITLE
Missing `info.yaml` from example segmentation app

### ISSUE THREAD

**Issue by srib** [Project-MONAI/MONAILabel#617]
[info.yaml](https://github.com/Project-MONAI/MONAILabel/blob/main/sample-apps/segmentation/info.yaml) missing from example [segmentation](https://github.com/Project-MONAI/MONAILabel/tree/main/sample-apps/segmentation) app.

**Comment by diazandr3s** [comment]
Hi @srib, thanks for raising this issue. 
I'm updating the Readme file for Segmentation App. There is no info.yaml anymore for any of the Apps. The latest version of the app consists of configs as part of app code rather than code and yaml. 

See this issue: https://github.com/Project-MONAI/MONAILabel/issues/585

Sorry for the confusion.

**Comment by srib** [comment]
Thanks, @diazandr3s!
