### ISSUE TITLE
Strange behaviour of Segment Editor in MONAI Label

### ISSUE THREAD

**Issue by diazandr3s** [Project-MONAI/MONAILabel#780]
**Describe the bug**

- Slice fill and slicer outline visibility is set to 0 by default.

![issue-segment-editor](https://user-images.githubusercontent.com/11991079/168340074-b9c9f1a7-266f-48c5-935b-d94b6b7dff30.png)

- Undo command in Segment Editor of MONAI Label doesn't work as good as using Segment Editor directly in Slicer. It removes everything instead of the last action.

- Order matters when editing a segment. If a user manually creates a segment and then performs inference, it deletes all segments in the scene. To avoid this, the user should first perform inference and then manually edit the segment. **_A warning that a segment is going to be deleted will help._**

**To Reproduce**

Please watch the video: https://user-images.githubusercontent.com/11991079/168338455-5d2285e4-999b-41a5-8c90-2c9d540e5c6a.mp4

**Expected behavior**

- Slice fill and slicer outline visibility is set to 1 by default.
- Undo last change only when using the undo option
- Show a warning before deleting the segment.

CC @nvahmadi

**Comment by lassoan** [comment]
> Undo command in Segment Editor of MONAI Label doesn't work as good as using Segment Editor directly in Slicer. It removes everything instead of the last action.

You need to call `saveStateForUndo()` before doing any operation that you would like to undo on the segmentation. This creates a checkpoint that the next undo operation will return to. In general, I would recommend to save one state for one user action on the GUI (that way a single action can reverted by a single click on Undo). `saveStateForUndo()` is available both in the segment editor widget and in the segment editor effect.

> Order matters when editing a segment. If a user manually creates a segment and then performs inference, it deletes all segments in the scene.

Most likely the issue is that the state is not saved when inference is performed. If inference is performed on a button click then in the button click handler, start with saving the undo state.

>  A warning that a segment is going to be deleted will help.

This may not be necessary, because undo/redo saves/restores added and deleted segments. If the user realizes that something did not go well then he should be able to undo the changes in the segmentation.

**Comment by diazandr3s** [comment]
Thanks for your comments, @lassoan 

Do you know what's the class or method to set slice fill and slicer outline visibility to 1 by default in the **_Segmentations_** module?

**Comment by diazandr3s** [comment]
Thanks all for your comments.

@lassoan, [here](https://github.com/Project-MONAI/MONAILabel/blob/main/plugins/slicer/MONAILabel/MONAILabel.py#L654) we set the `vtkMRMLSegmentEditorNode` to Segment Editor Widget.

Is this what you mean? Please let me know

**Comment by lassoan** [comment]
I've created a pull request that cleans up usage of segment editor widgets and segment editor nodes. It may fix problems related to segment editor nodes and widgets, because it avoids creation of many extra segment editor nodes and frequent switches between them.

https://github.com/Project-MONAI/MONAILabel/pull/806

**Comment by diazandr3s** [comment]
I just tested and it's working. Many thanks for your help, @lassoan.

Closing this issue.

**Comment by diazandr3s** [comment]
I just tested and it's working. Many thanks for your help, @lassoan.

Closing this issue.
